[Application]

# Login URL
base_url = https://www.linkedin.com/login/?trk=guest_homepage-basic_nav-header-signin
# Browser Options
browser = edge

# Wait Time (seconds)
implicit_wait = 10

# Test Credentials
valid_email = admin@test.com
valid_password = Admin@123

invalid_email = test123@test.com
invalid_password = WrongPassword

# Reports
report_path = Reports/

# Screenshots
screenshot_path = Screenshots/

# Logs
log_path = Logs/
